### ISSUE TITLE
latent resolution in calculating loss

### ISSUE THREAD

**Issue by Chenfeng1271** [Cominclip/BoxDiff-XL#1]
Hi, thank you for your contribution to applying Boxdiff in SDXL. However, I met some bugs when implementing this code. 

I see the latent updating code in [https://github.com/Cominclip/BoxDiff-XL/blob/bc19e5bae043f00c61c1dc686205e75f84d7ed83/pipeline/sdxl_pipeline_boxdiff.py#L695](url) is different from that on SD1.4.  Originally, Boxdiff calculated the attention map without unconditional branch. However, in your code, it seems add a uncondition text emb but still uses one latent [1,4,128,128]. I afraid this is a bug. So can u tell me how to debug this to achieve corresponding results? Thank u.

**Comment by Cominclip** [comment]
> Hi, thank you for your contribution to applying Boxdiff in SDXL. However, I met some bugs when implementing this code.
> 
> I see the latent updating code in [https://github.com/Cominclip/BoxDiff-XL/blob/bc19e5bae043f00c61c1dc686205e75f84d7ed83/pipeline/sdxl_pipeline_boxdiff.py#L695](url) is different from that on SD1.4. Originally, Boxdiff calculated the attention map without unconditional branch. However, in your code, it seems add a uncondition text emb but still uses one latent [1,4,128,128]. I afraid this is a bug. So can u tell me how to debug this to achieve corresponding results? Thank u.

Hi, thank you for your support in my work!
In fact, I have only completed the rough framework structure of BoxDiff-XL and have not yet verified if there are any bugs in it. Due to other urgent tasks that I need to handle recently, I am unable to assist you in fixing this bug for the time being. You can make the necessary modifications yourself or, if you can wait until the end of May when I have some free time, I can help you with the debugging. If you complete the debugging and would like to pull a request, we can work together to improve this project.

**Comment by Chenfeng1271** [comment]
Thank u for your reply. I fix the bug and the code is ready to run now. But the result is somewhat strange. I will pull a request and if u have time after May, we can discuss it.
![2_canvas](https://github.com/Cominclip/BoxDiff-XL/assets/24824628/d25b402d-f622-4985-bac4-6bd21057ebe4)
![2](https://github.com/Cominclip/BoxDiff-XL/assets/24824628/f3e84df9-988c-460a-8a16-eae4d38713e1)

**Comment by Chenfeng1271** [comment]
![image](https://github.com/Cominclip/BoxDiff-XL/assets/24824628/f24131be-e520-402f-9bb4-609570691111)
after change some hyperparameters...

**Comment by Cominclip** [comment]
> ![image](https://private-user-images.githubusercontent.com/24824628/329820552-f24131be-e520-402f-9bb4-609570691111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0ODc0NTUsIm5iZiI6MTcxNTQ4NzE1NSwicGF0aCI6Ii8yNDgyNDYyOC8zMjk4MjA1NTItZjI0MTMxYmUtZTUyMC00MDJmLTliYjQtNjA5NTcwNjkxMTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA0MTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzQzNjE3OTM3MTE0ZDkxYTljMTM3ZDkxNDVkZWU1NGJjMjBmMDQ5NTFhZTczMDdlNzdiZjU3NzcxN2RlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3_0V2OyXqt4SAPZgQlxqZ0_V7FNU9CVk8Qw9q4PIAMo) after change some hyperparameters...

Thank you very much for fixing the bug! From the results you gave, the SDXL-based BoxDiff seems to be working fine. I will invite you as a collaborator for this project, so that you can modify the project directly, and I will take some time recently to test the code and discuss further improvements with you.

**Comment by SWHL** [comment]
When I ran the [main repo code](https://github.com/Cominclip/BoxDiff-XL/tree/a15a60449385b451e0b5b1ffce8e4dfbc8c2bb52), the code :
```bash
CUDA_VISIBLE_DEVICES=4 python run_sd_boxdiff.py --prompt "A rabbit wearing sunglasses looks very proud"  --P 0.2 --L 1 --seeds [1,2,3,4,5,6,7,8,9] --token_indices [2,4] --bbox [[67,87,366,512],[66,130,364,262]] --sd_xl True
```

 I met the same strange result:

<img width="695" alt="image" src="https://github.com/user-attachments/assets/0251fe47-4269-42a1-bc9b-407d67f69b55">

I want to know how to change the hyperparameters to obatain the right results:
![image](https://github.com/user-attachments/assets/38a094d8-f54c-4170-8233-a4b98d8ce3f9)

Thanks

**Comment by Cominclip** [comment]
You can change --max_iter_to_alter and --weight_loss to do some more tests. In fact, these images are all normal because SDXL is unstable for images with a resolution of 512*512. If you want to generate more stable and higher quality images, you need to change the resolution to 1024*1024, but this will consume a lot of VRAM usage.
